[package]
name = "bbst-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
fp.workspace = true
procon-lg.workspace = true
rand.workspace = true

[dev-dependencies]
rand.workspace = true
criterion.workspace = true

[[bench]]
name = "bbst_bench"
harness = false
